if(DEFINED AETHER_PRECLAMP_SOURCE_CLOSURE_SHA256_V1)
  string(LENGTH "${AETHER_PRECLAMP_SOURCE_CLOSURE_SHA256_V1}"
         AETHER_PRECLAMP_SOURCE_CLOSURE_LENGTH)
else()
  set(AETHER_PRECLAMP_SOURCE_CLOSURE_LENGTH 0)
endif()
if(NOT AETHER_PRECLAMP_SOURCE_CLOSURE_LENGTH EQUAL 64 OR
   AETHER_PRECLAMP_SOURCE_CLOSURE_SHA256_V1 MATCHES "[^0-9a-f]")
  message(FATAL_ERROR
    "AETHER_PRECLAMP_SOURCE_CLOSURE_SHA256_V1 must be exactly 64 lowercase hex characters")
endif()
