// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-render/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/map_gaussian_to_intersects.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct RenderUniforms {
    viewmat: mat4x4<f32>,
    focal: vec2<f32>,
    img_size: vec2<u32>,
    tile_bounds: vec2<u32>,
    pixel_center: vec2<f32>,
    camera_position: vec4<f32>,
    sh_degree: u32,
    num_visible: u32,
    total_splats: u32,
    max_intersects: u32,
    background: vec4<f32>,
}

struct ProjectedSplat {
    xy_x: f32,
    xy_y: f32,
    conic_x: f32,
    conic_y: f32,
    conic_z: f32,
    color_r: f32,
    color_g: f32,
    color_b: f32,
    color_a: f32,
}

const TILE_WIDTH: u32 = 16u;

@group(0) @binding(0) 
var<storage> uniforms: RenderUniforms;
@group(0) @binding(1) 
var<storage> projected: array<ProjectedSplat>;
@group(0) @binding(2) 
var<storage> splat_cum_hit_counts: array<u32>;
@group(0) @binding(3) 
var<storage, read_write> tile_id_from_isect: array<u32>;
@group(0) @binding(4) 
var<storage, read_write> compact_gid_from_isect: array<u32>;
@group(0) @binding(5) 
var<storage, read_write> num_intersections: array<u32>;

fn get_bbox(center: vec2<f32>, dims: vec2<f32>, bounds: vec2<u32>) -> vec4<u32> {
    let min = vec2<u32>(clamp((center - dims), vec2(0f), vec2<f32>(bounds)));
    let max = vec2<u32>(clamp(((center + dims) + vec2(1f)), vec2(0f), vec2<f32>(bounds)));
    return vec4<u32>(min, max);
}

fn get_tile_bbox(pix_center: vec2<f32>, pix_extent: vec2<f32>, tile_bounds: vec2<u32>) -> vec4<u32> {
    let tile_center = (pix_center / vec2(16f));
    let tile_extent = (pix_extent / vec2(16f));
    let _e9 = get_bbox(tile_center, tile_extent, tile_bounds);
    return _e9;
}

fn inverse(m: mat2x2<f32>) -> mat2x2<f32> {
    let det = determinant(m);
    if (det <= 0f) {
        return mat2x2<f32>(vec2(0f), vec2(0f));
    }
    let inv_det = (1f / det);
    return mat2x2<f32>(vec2<f32>((m[1].y * inv_det), (-(m[0].y) * inv_det)), vec2<f32>((-(m[0].y) * inv_det), (m[0].x * inv_det)));
}

fn compute_bbox_extent(cov2d: mat2x2<f32>, power_threshold: f32) -> vec2<f32> {
    return vec2<f32>(sqrt(((2f * power_threshold) * cov2d[0].x)), sqrt(((2f * power_threshold) * cov2d[1].y)));
}

fn tile_rect(tile: vec2<u32>) -> vec4<f32> {
    let rect_min = vec2<f32>((tile * TILE_WIDTH));
    let rect_max = (rect_min + vec2(16f));
    return vec4<f32>(rect_min.x, rect_min.y, rect_max.x, rect_max.y);
}

fn calc_sigma(pixel_coord: vec2<f32>, conic: vec3<f32>, xy: vec2<f32>) -> f32 {
    let delta = (pixel_coord - xy);
    return ((0.5f * (((conic.x * delta.x) * delta.x) + ((conic.z * delta.y) * delta.y))) + ((conic.y * delta.x) * delta.y));
}

fn will_primitive_contribute(rect: vec4<f32>, mean: vec2<f32>, conic_1: vec3<f32>, power_threshold_1: f32) -> bool {
    let x_left = (mean.x < rect.x);
    let x_right = (mean.x > rect.z);
    let in_x_range = !((x_left || x_right));
    let y_above = (mean.y < rect.y);
    let y_below = (mean.y > rect.w);
    let in_y_range = !((y_above || y_below));
    if (in_x_range && in_y_range) {
        return true;
    }
    let closest_corner = vec2<f32>(select(rect.z, rect.x, x_left), select(rect.w, rect.y, y_above));
    let width = (rect.z - rect.x);
    let height = (rect.w - rect.y);
    let d = vec2<f32>(select(-(f32(width)), f32(width), x_left), select(-(f32(height)), f32(height), y_above));
    let diff = (mean - closest_corner);
    let t_max = vec2<f32>(select(clamp(((((d.x * conic_1.x) * diff.x) + ((d.x * conic_1.y) * diff.y)) / ((d.x * conic_1.x) * d.x)), 0f, 1f), 0f, in_y_range), select(clamp(((((d.y * conic_1.y) * diff.x) + ((d.y * conic_1.z) * diff.y)) / ((d.y * conic_1.z) * d.y)), 0f, 1f), 0f, in_x_range));
    let max_contribution_point = (closest_corner + (t_max * d));
    let _e91 = calc_sigma(mean, conic_1, max_contribution_point);
    return (_e91 <= power_threshold_1);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
    var num_tiles_hit: u32 = 0u;
    var tile_idx: u32 = 0u;

    let compact_gid = gid.x;
    if (gid.x == 0u) {
        let _e11 = uniforms.num_visible;
        let _e13 = splat_cum_hit_counts[_e11];
        num_intersections[0] = _e13;
    }
    let _e16 = uniforms.num_visible;
    if (compact_gid >= _e16) {
        return;
    }
    let projected_1 = projected[compact_gid];
    let mean2d = vec2<f32>(projected_1.xy_x, projected_1.xy_y);
    let conic_2 = vec3<f32>(projected_1.conic_x, projected_1.conic_y, projected_1.conic_z);
    let opac = projected_1.color_a;
    let power_threshold_2 = log((opac * 255f));
    let _e39 = inverse(mat2x2<f32>(vec2<f32>(conic_2.x, conic_2.y), vec2<f32>(conic_2.y, conic_2.z)));
    let _e40 = compute_bbox_extent(_e39, power_threshold_2);
    let _e43 = uniforms.tile_bounds;
    let _e44 = get_tile_bbox(mean2d, _e40, _e43);
    let tile_bbox_min = _e44.xy;
    let tile_bbox_max = _e44.zw;
    let base_isect_id = splat_cum_hit_counts[compact_gid];
    let tile_bbox_width = (tile_bbox_max.x - tile_bbox_min.x);
    let num_tiles_bbox = ((tile_bbox_max.y - tile_bbox_min.y) * tile_bbox_width);
    loop {
        let _e58 = tile_idx;
        if (_e58 < num_tiles_bbox) {
        } else {
            break;
        }
        {
            let _e60 = tile_idx;
            let tx = ((_e60 % tile_bbox_width) + tile_bbox_min.x);
            let _e64 = tile_idx;
            let ty = ((_e64 / tile_bbox_width) + tile_bbox_min.y);
            let _e69 = tile_rect(vec2<u32>(tx, ty));
            let _e70 = will_primitive_contribute(_e69, mean2d, conic_2, power_threshold_2);
            if _e70 {
                let _e74 = uniforms.tile_bounds.x;
                let tile_id = (tx + (ty * _e74));
                let _e78 = num_tiles_hit;
                let isect_id = (base_isect_id + _e78);
                tile_id_from_isect[isect_id] = tile_id;
                compact_gid_from_isect[isect_id] = compact_gid;
                let _e85 = num_tiles_hit;
                num_tiles_hit = (_e85 + 1u);
            }
        }
        continuing {
            let _e88 = tile_idx;
            tile_idx = (_e88 + 1u);
        }
    }
    return;
}

