// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-prefix-sum/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/prefix_sum_add_scanned_sums.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

const THREADS_PER_GROUP: u32 = 512u;

@group(0) @binding(0) 
var<storage> input: array<u32>;
@group(0) @binding(1) 
var<storage, read_write> output: array<u32>;

@compute @workgroup_size(512, 1, 1) 
fn main(@builtin(global_invocation_id) id: vec3<u32>, @builtin(workgroup_id) wid: vec3<u32>) {
    if (id.x < arrayLength((&output))) {
        let _e12 = input[wid.x];
        let _e13 = output[id.x];
        output[id.x] = (_e13 + _e12);
        return;
    } else {
        return;
    }
}

