// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-prefix-sum/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/prefix_sum_scan.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

const THREADS_PER_GROUP: u32 = 512u;

@group(0) @binding(0) 
var<storage> input: array<u32>;
var<workgroup> bucket: array<u32, 512>;
@group(0) @binding(1) 
var<storage, read_write> output: array<u32>;

fn groupScan(id_1: u32, gi: u32, x_1: u32) {
    var t: u32 = 1u;
    var temp: u32;

    bucket[gi] = x_1;
    loop {
        let _e6 = t;
        if (_e6 < THREADS_PER_GROUP) {
        } else {
            break;
        }
        {
            workgroupBarrier();
            let _e11 = bucket[gi];
            temp = _e11;
            let _e13 = t;
            if (gi >= _e13) {
                let _e16 = t;
                let _e19 = bucket[(gi - _e16)];
                let _e20 = temp;
                temp = (_e20 + _e19);
            }
            workgroupBarrier();
            let _e24 = temp;
            bucket[gi] = _e24;
        }
        continuing {
            let _e25 = t;
            t = (_e25 * 2u);
        }
    }
    if (id_1 < arrayLength((&output))) {
        let _e36 = bucket[gi];
        output[id_1] = _e36;
        return;
    } else {
        return;
    }
}

@compute @workgroup_size(512, 1, 1) 
fn main(@builtin(global_invocation_id) id: vec3<u32>, @builtin(local_invocation_index) gid: u32) {
    var x: u32 = 0u;

    if (id.x < arrayLength((&input))) {
        let _e9 = input[id.x];
        x = _e9;
    }
    let _e12 = x;
    groupScan(id.x, gid, _e12);
    return;
}

