// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-render-bwd/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/project_backwards.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct RenderUniforms {
    viewmat: mat4x4<f32>,
    focal: vec2<f32>,
    img_size: vec2<u32>,
    tile_bounds: vec2<u32>,
    pixel_center: vec2<f32>,
    camera_position: vec4<f32>,
    sh_degree: u32,
    num_visible: u32,
    total_splats: u32,
    max_intersects: u32,
    background: vec4<f32>,
}

struct PackedVec3 {
    x: f32,
    y: f32,
    z: f32,
}

struct ShCoeffs {
    b0_c0_: vec3<f32>,
    b1_c0_: vec3<f32>,
    b1_c1_: vec3<f32>,
    b1_c2_: vec3<f32>,
    b2_c0_: vec3<f32>,
    b2_c1_: vec3<f32>,
    b2_c2_: vec3<f32>,
    b2_c3_: vec3<f32>,
    b2_c4_: vec3<f32>,
    b3_c0_: vec3<f32>,
    b3_c1_: vec3<f32>,
    b3_c2_: vec3<f32>,
    b3_c3_: vec3<f32>,
    b3_c4_: vec3<f32>,
    b3_c5_: vec3<f32>,
    b3_c6_: vec3<f32>,
    b4_c0_: vec3<f32>,
    b4_c1_: vec3<f32>,
    b4_c2_: vec3<f32>,
    b4_c3_: vec3<f32>,
    b4_c4_: vec3<f32>,
    b4_c5_: vec3<f32>,
    b4_c6_: vec3<f32>,
    b4_c7_: vec3<f32>,
    b4_c8_: vec3<f32>,
}

const COV_BLUR: f32 = 0.3f;
const SH_C0_: f32 = 0.2820948f;

@group(0) @binding(0) 
var<storage> uniforms: RenderUniforms;
@group(0) @binding(1) 
var<storage> means: array<PackedVec3>;
@group(0) @binding(2) 
var<storage> log_scales: array<PackedVec3>;
@group(0) @binding(3) 
var<storage> quats: array<vec4<f32>>;
@group(0) @binding(4) 
var<storage> global_from_compact_gid: array<u32>;
@group(0) @binding(5) 
var<storage> v_grads: array<vec4<f32>>;
@group(0) @binding(6) 
var<storage, read_write> v_means: array<PackedVec3>;
@group(0) @binding(7) 
var<storage, read_write> v_scales: array<PackedVec3>;
@group(0) @binding(8) 
var<storage, read_write> v_quats: array<vec4<f32>>;
@group(0) @binding(9) 
var<storage, read_write> v_coeffs_1: array<f32>;

fn quat_to_mat(quat: vec4<f32>) -> mat3x3<f32> {
    let w = quat.x;
    let x = quat.y;
    let y = quat.z;
    let z = quat.w;
    let x2_ = (x * x);
    let y2_ = (y * y);
    let z2_ = (z * z);
    let xy = (x * y);
    let xz = (x * z);
    let yz = (y * z);
    let wx = (w * x);
    let wy = (w * y);
    let wz = (w * z);
    return mat3x3<f32>(vec3<f32>((1f - (2f * (y2_ + z2_))), (2f * (xy + wz)), (2f * (xz - wy))), vec3<f32>((2f * (xy - wz)), (1f - (2f * (x2_ + z2_))), (2f * (yz + wx))), vec3<f32>((2f * (xz + wy)), (2f * (yz - wx)), (1f - (2f * (x2_ + y2_)))));
}

fn scale_to_mat(scale: vec3<f32>) -> mat3x3<f32> {
    return mat3x3<f32>(vec3<f32>(scale.x, 0f, 0f), vec3<f32>(0f, scale.y, 0f), vec3<f32>(0f, 0f, scale.z));
}

fn calc_cam_J(mean_c: vec3<f32>, focal: vec2<f32>, img_size: vec2<u32>, pixel_center: vec2<f32>) -> mat3x2<f32> {
    let lims_pos = (((1.15f * vec2<f32>(img_size.xy)) - pixel_center) / focal);
    let lims_neg = (((-0.15f * vec2<f32>(img_size.xy)) - pixel_center) / focal);
    let rz = (1f / mean_c.z);
    let uv_clipped = clamp((mean_c.xy * rz), lims_neg, lims_pos);
    let duv_dxy = (focal * rz);
    let J_1 = mat3x2<f32>(vec2<f32>(duv_dxy.x, 0f), vec2<f32>(0f, duv_dxy.y), (-(duv_dxy) * uv_clipped));
    return J_1;
}

fn calc_cov2d(cov3d: mat3x3<f32>, mean_c_1: vec3<f32>, focal_1: vec2<f32>, img_size_1: vec2<u32>, pixel_center_1: vec2<f32>, viewmat: mat4x4<f32>) -> mat2x2<f32> {
    var cov2d: mat2x2<f32>;

    let R = mat3x3<f32>(viewmat[0].xyz, viewmat[1].xyz, viewmat[2].xyz);
    let covar_cam = ((R * cov3d) * transpose(R));
    let _e16 = calc_cam_J(mean_c_1, focal_1, img_size_1, pixel_center_1);
    cov2d = ((_e16 * covar_cam) * transpose(_e16));
    let _e24 = cov2d[0][0];
    cov2d[0][0] = (_e24 + COV_BLUR);
    let _e29 = cov2d[1][1];
    cov2d[1][1] = (_e29 + COV_BLUR);
    let _e31 = cov2d;
    return _e31;
}

fn inverse(m: mat2x2<f32>) -> mat2x2<f32> {
    let det = determinant(m);
    if (det <= 0f) {
        return mat2x2<f32>(vec2(0f), vec2(0f));
    }
    let inv_det = (1f / det);
    return mat2x2<f32>(vec2<f32>((m[1].y * inv_det), (-(m[0].y) * inv_det)), vec2<f32>((-(m[0].y) * inv_det), (m[0].x * inv_det)));
}

fn as_vec(packed: PackedVec3) -> vec3<f32> {
    return vec3<f32>(packed.x, packed.y, packed.z);
}

fn as_packed(vec: vec3<f32>) -> PackedVec3 {
    return PackedVec3(vec.x, vec.y, vec.z);
}

fn sh_coeffs_to_color_fast_vjp(degree: u32, viewdir: vec3<f32>, v_colors: vec3<f32>) -> ShCoeffs {
    var v_coeffs: ShCoeffs = ShCoeffs();

    v_coeffs.b0_c0_ = (SH_C0_ * v_colors);
    if (degree == 0u) {
        let _e9 = v_coeffs;
        return _e9;
    }
    let x_1 = viewdir.x;
    let y_1 = viewdir.y;
    let z_1 = viewdir.z;
    v_coeffs.b1_c0_ = ((-(0.48860252f) * y_1) * v_colors);
    v_coeffs.b1_c1_ = ((0.48860252f * z_1) * v_colors);
    v_coeffs.b1_c2_ = ((-(0.48860252f) * x_1) * v_colors);
    if (degree == 1u) {
        let _e28 = v_coeffs;
        return _e28;
    }
    let z2_1 = (z_1 * z_1);
    let fTmp0B = (-1.0925485f * z_1);
    let fC1_ = ((x_1 * x_1) - (y_1 * y_1));
    let fS1_ = ((2f * x_1) * y_1);
    let pSH6_ = ((0.9461747f * z2_1) - 0.31539157f);
    let pSH7_ = (fTmp0B * x_1);
    let pSH5_ = (fTmp0B * y_1);
    let pSH8_ = (0.54627424f * fC1_);
    let pSH4_ = (0.54627424f * fS1_);
    v_coeffs.b2_c0_ = (pSH4_ * v_colors);
    v_coeffs.b2_c1_ = (pSH5_ * v_colors);
    v_coeffs.b2_c2_ = (pSH6_ * v_colors);
    v_coeffs.b2_c3_ = (pSH7_ * v_colors);
    v_coeffs.b2_c4_ = (pSH8_ * v_colors);
    if (degree == 2u) {
        let _e59 = v_coeffs;
        return _e59;
    }
    let fTmp0C = ((-2.285229f * z2_1) + 0.4570458f);
    let fTmp1B = (1.4453057f * z_1);
    let fC2_ = ((x_1 * fC1_) - (y_1 * fS1_));
    let fS2_ = ((x_1 * fS1_) + (y_1 * fC1_));
    let pSH12_ = (z_1 * ((1.8658817f * z2_1) - 1.119529f));
    let pSH13_ = (fTmp0C * x_1);
    let pSH11_ = (fTmp0C * y_1);
    let pSH14_ = (fTmp1B * fC1_);
    let pSH10_ = (fTmp1B * fS1_);
    let pSH15_ = (-0.5900436f * fC2_);
    let pSH9_ = (-0.5900436f * fS2_);
    v_coeffs.b3_c0_ = (pSH9_ * v_colors);
    v_coeffs.b3_c1_ = (pSH10_ * v_colors);
    v_coeffs.b3_c2_ = (pSH11_ * v_colors);
    v_coeffs.b3_c3_ = (pSH12_ * v_colors);
    v_coeffs.b3_c4_ = (pSH13_ * v_colors);
    v_coeffs.b3_c5_ = (pSH14_ * v_colors);
    v_coeffs.b3_c6_ = (pSH15_ * v_colors);
    if (degree == 3u) {
        let _e100 = v_coeffs;
        return _e100;
    }
    let fTmp0D = (z_1 * ((-4.683326f * z2_1) + 2.0071397f));
    let fTmp1C = ((3.3116114f * z2_1) - 0.47308734f);
    let fTmp2B = (-1.7701308f * z_1);
    let fC3_ = ((x_1 * fC2_) - (y_1 * fS2_));
    let fS3_ = ((x_1 * fS2_) + (y_1 * fC2_));
    let pSH20_ = (((1.9843135f * z_1) * pSH12_) + (-1.0062306f * pSH6_));
    let pSH21_ = (fTmp0D * x_1);
    let pSH19_ = (fTmp0D * y_1);
    let pSH22_ = (fTmp1C * fC1_);
    let pSH18_ = (fTmp1C * fS1_);
    let pSH23_ = (fTmp2B * fC2_);
    let pSH17_ = (fTmp2B * fS2_);
    let pSH24_ = (0.6258357f * fC3_);
    let pSH16_ = (0.6258357f * fS3_);
    v_coeffs.b4_c0_ = (pSH16_ * v_colors);
    v_coeffs.b4_c1_ = (pSH17_ * v_colors);
    v_coeffs.b4_c2_ = (pSH18_ * v_colors);
    v_coeffs.b4_c3_ = (pSH19_ * v_colors);
    v_coeffs.b4_c4_ = (pSH20_ * v_colors);
    v_coeffs.b4_c5_ = (pSH21_ * v_colors);
    v_coeffs.b4_c6_ = (pSH22_ * v_colors);
    v_coeffs.b4_c7_ = (pSH23_ * v_colors);
    v_coeffs.b4_c8_ = (pSH24_ * v_colors);
    let _e151 = v_coeffs;
    return _e151;
}

fn num_sh_coeffs(degree_1: u32) -> u32 {
    return ((degree_1 + 1u) * (degree_1 + 1u));
}

fn write_coeffs(base_id_1: ptr<function, u32>, val: vec3<f32>) {
    let _e1 = (*base_id_1);
    v_coeffs_1[(_e1 + 0u)] = val.x;
    let _e8 = (*base_id_1);
    v_coeffs_1[(_e8 + 1u)] = val.y;
    let _e14 = (*base_id_1);
    v_coeffs_1[(_e14 + 2u)] = val.z;
    let _e21 = (*base_id_1);
    (*base_id_1) = (_e21 + 3u);
    return;
}

fn normalize_vjp(quat_1: vec4<f32>) -> mat4x4<f32> {
    let quat_sqr = (quat_1 * quat_1);
    let quat_len_sqr = dot(quat_1, quat_1);
    let quat_len = sqrt(quat_len_sqr);
    let cross_complex = (-(quat_1.xyz) * quat_1.yzx);
    let cross_scalar = (-(quat_1.xyz) * quat_1.w);
    return (mat4x4<f32>(vec4<f32>((quat_len_sqr - quat_sqr.x), cross_complex.x, cross_complex.z, cross_scalar.x), vec4<f32>(cross_complex.x, (quat_len_sqr - quat_sqr.y), cross_complex.y, cross_scalar.y), vec4<f32>(cross_complex.z, cross_complex.y, (quat_len_sqr - quat_sqr.z), cross_scalar.z), vec4<f32>(cross_scalar.x, cross_scalar.y, cross_scalar.z, (quat_len_sqr - quat_sqr.w))) * (1f / (quat_len * quat_len_sqr)));
}

fn quat_to_mat_vjp(quat_2: vec4<f32>, v_R: mat3x3<f32>) -> vec4<f32> {
    let w_1 = quat_2.x;
    let x_2 = quat_2.y;
    let y_2 = quat_2.z;
    let z_2 = quat_2.w;
    return (vec4<f32>((((x_2 * (v_R[1].z - v_R[2].y)) + (y_2 * (v_R[2].x - v_R[0].z))) + (z_2 * (v_R[0].y - v_R[1].x))), (((((-2f * x_2) * (v_R[1].y + v_R[2].z)) + (y_2 * (v_R[0].y + v_R[1].x))) + (z_2 * (v_R[0].z + v_R[2].x))) + (w_1 * (v_R[1].z - v_R[2].y))), ((((x_2 * (v_R[0].y + v_R[1].x)) - ((2f * y_2) * (v_R[0].x + v_R[2].z))) + (z_2 * (v_R[1].z + v_R[2].y))) + (w_1 * (v_R[2].x - v_R[0].z))), ((((x_2 * (v_R[0].z + v_R[2].x)) + (y_2 * (v_R[1].z + v_R[2].y))) - ((2f * z_2) * (v_R[0].x + v_R[1].y))) + (w_1 * (v_R[0].y - v_R[1].x)))) * 2f);
}

fn inverse_vjp(Minv: mat2x2<f32>, v_Minv: mat2x2<f32>) -> mat2x2<f32> {
    return ((mat2x2<f32>(-(Minv[0]), -(Minv[1])) * v_Minv) * Minv);
}

fn outer_product(a: vec3<f32>, b: vec3<f32>) -> mat3x3<f32> {
    return mat3x3<f32>(vec3<f32>((a.x * b.x), (a.x * b.y), (a.x * b.z)), vec3<f32>((a.y * b.x), (a.y * b.y), (a.y * b.z)), vec3<f32>((a.z * b.x), (a.z * b.y), (a.z * b.z)));
}

fn persp_proj_vjp(J: mat3x2<f32>, mean3d: vec3<f32>, cov3d_1: mat3x3<f32>, focal_2: vec2<f32>, pixel_center_2: vec2<f32>, img_size_2: vec2<u32>, v_cov2d: mat2x2<f32>, v_mean2d: vec2<f32>) -> vec3<f32> {
    var v_mean3d: vec3<f32>;

    let x_3 = mean3d.x;
    let y_3 = mean3d.y;
    let z_3 = mean3d.z;
    let rz_1 = (1f / mean3d.z);
    let rz2_ = (rz_1 * rz_1);
    v_mean3d = vec3<f32>(((focal_2.x * rz_1) * v_mean2d.x), ((focal_2.y * rz_1) * v_mean2d.y), (-((((focal_2.x * x_3) * v_mean2d.x) + ((focal_2.y * y_3) * v_mean2d.y))) * rz2_));
    let rz3_ = (rz2_ * rz_1);
    let v_J = (((v_cov2d * J) * transpose(cov3d_1)) + ((transpose(v_cov2d) * J) * cov3d_1));
    let tan_fov = ((0.5f * vec2<f32>(img_size_2.xy)) / focal_2);
    let lims_pos_1 = (((vec2<f32>(img_size_2.xy) - pixel_center_2) / focal_2) + (0.3f * tan_fov));
    let lims_neg_1 = ((pixel_center_2 / focal_2) + (0.3f * tan_fov));
    let t = (mean3d.z * clamp((mean3d.xy * rz_1), -(lims_neg_1), lims_pos_1));
    let lim_x_pos = lims_pos_1.x;
    let lim_x_neg = lims_neg_1.x;
    let lim_y_pos = lims_pos_1.y;
    let lim_y_neg = lims_neg_1.y;
    let tx = t.x;
    let ty = t.y;
    if (((x_3 * rz_1) <= lim_x_pos) && ((x_3 * rz_1) >= -(lim_x_neg))) {
        let _e85 = v_mean3d.x;
        v_mean3d.x = (_e85 + ((-(focal_2.x) * rz2_) * v_J[2].x));
    } else {
        let _e95 = v_mean3d.z;
        v_mean3d.z = (_e95 + (((-(focal_2.x) * rz3_) * v_J[2].x) * tx));
    }
    if (((y_3 * rz_1) <= lim_y_pos) && ((y_3 * rz_1) >= -(lim_y_neg))) {
        let _e110 = v_mean3d.y;
        v_mean3d.y = (_e110 + ((-(focal_2.y) * rz2_) * v_J[2].y));
    } else {
        let _e120 = v_mean3d.z;
        v_mean3d.z = (_e120 + (((-(focal_2.y) * rz3_) * v_J[2].y) * ty));
    }
    let _e153 = v_mean3d.z;
    v_mean3d.z = (_e153 + (((((-(focal_2.x) * rz2_) * v_J[0].x) - ((focal_2.y * rz2_) * v_J[1].y)) + ((((2f * focal_2.x) * tx) * rz3_) * v_J[2].x)) + ((((2f * focal_2.y) * ty) * rz3_) * v_J[2].y)));
    let _e155 = v_mean3d;
    return _e155;
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
    var base_id: u32;

    let compact_gid = gid.x;
    let _e4 = uniforms.num_visible;
    if (compact_gid >= _e4) {
        return;
    }
    let global_gid = global_from_compact_gid[compact_gid];
    let viewmat_1 = uniforms.viewmat;
    let focal_3 = uniforms.focal;
    let img_size_3 = uniforms.img_size;
    let pixel_center_3 = uniforms.pixel_center;
    let _e23 = means[global_gid];
    let _e24 = as_vec(_e23);
    let _e27 = log_scales[global_gid];
    let _e28 = as_vec(_e27);
    let scale_1 = exp(_e28);
    let quat_unorm = quats[global_gid];
    let quat_3 = normalize(quat_unorm);
    let grad0_ = v_grads[(global_gid * 2u)];
    let grad1_ = v_grads[((global_gid * 2u) + 1u)];
    let v_mean2d_1 = vec2<f32>(grad0_.x, grad0_.y);
    let v_conics = vec3<f32>(grad0_.z, grad0_.w, grad1_.x);
    let v_color = vec3<f32>(grad1_.y, grad1_.z, grad1_.w);
    let _e59 = uniforms.camera_position;
    let viewdir_1 = normalize((_e24 - _e59.xyz));
    let sh_degree = uniforms.sh_degree;
    let _e66 = sh_coeffs_to_color_fast_vjp(sh_degree, viewdir_1, v_color);
    let _e67 = num_sh_coeffs(sh_degree);
    base_id = ((global_gid * _e67) * 3u);
    write_coeffs((&base_id), _e66.b0_c0_);
    if (sh_degree > 0u) {
        write_coeffs((&base_id), _e66.b1_c0_);
        write_coeffs((&base_id), _e66.b1_c1_);
        write_coeffs((&base_id), _e66.b1_c2_);
        if (sh_degree > 1u) {
            write_coeffs((&base_id), _e66.b2_c0_);
            write_coeffs((&base_id), _e66.b2_c1_);
            write_coeffs((&base_id), _e66.b2_c2_);
            write_coeffs((&base_id), _e66.b2_c3_);
            write_coeffs((&base_id), _e66.b2_c4_);
            if (sh_degree > 2u) {
                write_coeffs((&base_id), _e66.b3_c0_);
                write_coeffs((&base_id), _e66.b3_c1_);
                write_coeffs((&base_id), _e66.b3_c2_);
                write_coeffs((&base_id), _e66.b3_c3_);
                write_coeffs((&base_id), _e66.b3_c4_);
                write_coeffs((&base_id), _e66.b3_c5_);
                write_coeffs((&base_id), _e66.b3_c6_);
                if (sh_degree > 3u) {
                    write_coeffs((&base_id), _e66.b4_c0_);
                    write_coeffs((&base_id), _e66.b4_c1_);
                    write_coeffs((&base_id), _e66.b4_c2_);
                    write_coeffs((&base_id), _e66.b4_c3_);
                    write_coeffs((&base_id), _e66.b4_c4_);
                    write_coeffs((&base_id), _e66.b4_c5_);
                    write_coeffs((&base_id), _e66.b4_c6_);
                    write_coeffs((&base_id), _e66.b4_c7_);
                    write_coeffs((&base_id), _e66.b4_c8_);
                }
            }
        }
    }
    let R_1 = mat3x3<f32>(viewmat_1[0].xyz, viewmat_1[1].xyz, viewmat_1[2].xyz);
    let mean_c_2 = ((R_1 * _e24) + viewmat_1[3].xyz);
    let rz_2 = (1f / mean_c_2.z);
    let rz2_1 = (rz_2 * rz_2);
    let _e120 = quat_to_mat(quat_3);
    let _e121 = scale_to_mat(scale_1);
    let M = (_e120 * _e121);
    let covar = (M * transpose(M));
    let _e125 = calc_cov2d(covar, mean_c_2, focal_3, img_size_3, pixel_center_3, viewmat_1);
    let _e126 = inverse(_e125);
    let v_covar2d_inv = mat2x2<f32>(vec2<f32>(v_conics.x, (v_conics.y * 0.5f)), vec2<f32>((v_conics.y * 0.5f), v_conics.z));
    let _e138 = inverse_vjp(_e126, v_covar2d_inv);
    let covar_c = ((R_1 * covar) * transpose(R_1));
    let _e142 = calc_cam_J(mean_c_2, focal_3, img_size_3, pixel_center_3);
    let _e143 = persp_proj_vjp(_e142, mean_c_2, covar_c, focal_3, pixel_center_3, img_size_3, _e138, v_mean2d_1);
    let v_covar_c = ((transpose(_e142) * _e138) * _e142);
    let v_mean = (transpose(R_1) * _e143);
    let v_covar = ((transpose(R_1) * v_covar_c) * R_1);
    let v_M = ((v_covar + transpose(v_covar)) * M);
    let v_scale = vec3<f32>(dot(_e120[0], v_M[0]), dot(_e120[1], v_M[1]), dot(_e120[2], v_M[2]));
    let v_scale_exp = (v_scale * scale_1);
    let _e166 = normalize_vjp(quat_unorm);
    let _e168 = quat_to_mat_vjp(quat_3, (v_M * _e121));
    let v_quat = (_e166 * _e168);
    let _e172 = as_packed(v_mean);
    v_means[global_gid] = _e172;
    let _e175 = as_packed(v_scale_exp);
    v_scales[global_gid] = _e175;
    v_quats[global_gid] = v_quat;
    return;
}

