// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-render/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/project_visible.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct RenderUniforms {
    viewmat: mat4x4<f32>,
    focal: vec2<f32>,
    img_size: vec2<u32>,
    tile_bounds: vec2<u32>,
    pixel_center: vec2<f32>,
    camera_position: vec4<f32>,
    sh_degree: u32,
    num_visible: atomic<u32>,
    total_splats: u32,
    max_intersects: u32,
    background: vec4<f32>,
}

struct ProjectedSplat {
    xy_x: f32,
    xy_y: f32,
    conic_x: f32,
    conic_y: f32,
    conic_z: f32,
    color_r: f32,
    color_g: f32,
    color_b: f32,
    color_a: f32,
}

struct PackedVec3 {
    x: f32,
    y: f32,
    z: f32,
}

struct IsectInfo {
    compact_gid: u32,
    tile_id: u32,
}

struct ShCoeffs {
    b0_c0_: vec3<f32>,
    b1_c0_: vec3<f32>,
    b1_c1_: vec3<f32>,
    b1_c2_: vec3<f32>,
    b2_c0_: vec3<f32>,
    b2_c1_: vec3<f32>,
    b2_c2_: vec3<f32>,
    b2_c3_: vec3<f32>,
    b2_c4_: vec3<f32>,
    b3_c0_: vec3<f32>,
    b3_c1_: vec3<f32>,
    b3_c2_: vec3<f32>,
    b3_c3_: vec3<f32>,
    b3_c4_: vec3<f32>,
    b3_c5_: vec3<f32>,
    b3_c6_: vec3<f32>,
    b4_c0_: vec3<f32>,
    b4_c1_: vec3<f32>,
    b4_c2_: vec3<f32>,
    b4_c3_: vec3<f32>,
    b4_c4_: vec3<f32>,
    b4_c5_: vec3<f32>,
    b4_c6_: vec3<f32>,
    b4_c7_: vec3<f32>,
    b4_c8_: vec3<f32>,
}

const COV_BLUR: f32 = 0.3f;
const SH_C0_: f32 = 0.2820948f;

@group(0) @binding(0) 
var<storage, read_write> uniforms: RenderUniforms;
@group(0) @binding(1) 
var<storage> means: array<PackedVec3>;
@group(0) @binding(2) 
var<storage> log_scales: array<PackedVec3>;
@group(0) @binding(3) 
var<storage> quats: array<vec4<f32>>;
@group(0) @binding(4) 
var<storage> coeffs: array<PackedVec3>;
@group(0) @binding(5) 
var<storage> raw_opacities: array<f32>;
@group(0) @binding(6) 
var<storage> global_from_compact_gid: array<u32>;
@group(0) @binding(7) 
var<storage, read_write> projected: array<ProjectedSplat>;

fn create_projected_splat(xy: vec2<f32>, conic: vec3<f32>, color_1: vec4<f32>) -> ProjectedSplat {
    return ProjectedSplat(xy.x, xy.y, conic.x, conic.y, conic.z, color_1.x, color_1.y, color_1.z, color_1.w);
}

fn sigmoid(x: f32) -> f32 {
    return (1f / (1f + exp(-(x))));
}

fn quat_to_mat(quat: vec4<f32>) -> mat3x3<f32> {
    let w = quat.x;
    let x_1 = quat.y;
    let y = quat.z;
    let z = quat.w;
    let x2_ = (x_1 * x_1);
    let y2_ = (y * y);
    let z2_ = (z * z);
    let xy_1 = (x_1 * y);
    let xz = (x_1 * z);
    let yz = (y * z);
    let wx = (w * x_1);
    let wy = (w * y);
    let wz = (w * z);
    return mat3x3<f32>(vec3<f32>((1f - (2f * (y2_ + z2_))), (2f * (xy_1 + wz)), (2f * (xz - wy))), vec3<f32>((2f * (xy_1 - wz)), (1f - (2f * (x2_ + z2_))), (2f * (yz + wx))), vec3<f32>((2f * (xz + wy)), (2f * (yz - wx)), (1f - (2f * (x2_ + y2_)))));
}

fn scale_to_mat(scale: vec3<f32>) -> mat3x3<f32> {
    return mat3x3<f32>(vec3<f32>(scale.x, 0f, 0f), vec3<f32>(0f, scale.y, 0f), vec3<f32>(0f, 0f, scale.z));
}

fn calc_cov3d(scale_1: vec3<f32>, quat_1: vec4<f32>) -> mat3x3<f32> {
    let _e1 = quat_to_mat(quat_1);
    let _e3 = scale_to_mat(scale_1);
    let M = (_e1 * _e3);
    return (M * transpose(M));
}

fn calc_cam_J(mean_c: vec3<f32>, focal: vec2<f32>, img_size: vec2<u32>, pixel_center: vec2<f32>) -> mat3x2<f32> {
    let lims_pos = (((1.15f * vec2<f32>(img_size.xy)) - pixel_center) / focal);
    let lims_neg = (((-0.15f * vec2<f32>(img_size.xy)) - pixel_center) / focal);
    let rz = (1f / mean_c.z);
    let uv_clipped = clamp((mean_c.xy * rz), lims_neg, lims_pos);
    let duv_dxy = (focal * rz);
    let J = mat3x2<f32>(vec2<f32>(duv_dxy.x, 0f), vec2<f32>(0f, duv_dxy.y), (-(duv_dxy) * uv_clipped));
    return J;
}

fn calc_cov2d(cov3d: mat3x3<f32>, mean_c_1: vec3<f32>, focal_1: vec2<f32>, img_size_1: vec2<u32>, pixel_center_1: vec2<f32>, viewmat: mat4x4<f32>) -> mat2x2<f32> {
    var cov2d: mat2x2<f32>;

    let R = mat3x3<f32>(viewmat[0].xyz, viewmat[1].xyz, viewmat[2].xyz);
    let covar_cam = ((R * cov3d) * transpose(R));
    let _e16 = calc_cam_J(mean_c_1, focal_1, img_size_1, pixel_center_1);
    cov2d = ((_e16 * covar_cam) * transpose(_e16));
    let _e24 = cov2d[0][0];
    cov2d[0][0] = (_e24 + COV_BLUR);
    let _e29 = cov2d[1][1];
    cov2d[1][1] = (_e29 + COV_BLUR);
    let _e31 = cov2d;
    return _e31;
}

fn inverse(m: mat2x2<f32>) -> mat2x2<f32> {
    let det = determinant(m);
    if (det <= 0f) {
        return mat2x2<f32>(vec2(0f), vec2(0f));
    }
    let inv_det = (1f / det);
    return mat2x2<f32>(vec2<f32>((m[1].y * inv_det), (-(m[0].y) * inv_det)), vec2<f32>((-(m[0].y) * inv_det), (m[0].x * inv_det)));
}

fn as_vec(packed: PackedVec3) -> vec3<f32> {
    return vec3<f32>(packed.x, packed.y, packed.z);
}

fn sh_coeffs_to_color(degree: u32, viewdir: vec3<f32>, sh_1: ShCoeffs) -> vec3<f32> {
    var colors: vec3<f32>;

    colors = (SH_C0_ * sh_1.b0_c0_);
    if (degree == 0u) {
        let _e8 = colors;
        return _e8;
    }
    let x_2 = viewdir.x;
    let y_1 = viewdir.y;
    let z_1 = viewdir.z;
    let _e24 = colors;
    colors = (_e24 + (0.48860252f * (((-(y_1) * sh_1.b1_c0_) + (z_1 * sh_1.b1_c1_)) - (x_2 * sh_1.b1_c2_))));
    if (degree == 1u) {
        let _e28 = colors;
        return _e28;
    }
    let z2_1 = (z_1 * z_1);
    let fTmp0B = (-1.0925485f * z_1);
    let fC1_ = ((x_2 * x_2) - (y_1 * y_1));
    let fS1_ = ((2f * x_2) * y_1);
    let pSH6_ = ((0.9461747f * z2_1) - 0.31539157f);
    let pSH7_ = (fTmp0B * x_2);
    let pSH5_ = (fTmp0B * y_1);
    let pSH8_ = (0.54627424f * fC1_);
    let pSH4_ = (0.54627424f * fS1_);
    let _e61 = colors;
    colors = (_e61 + (((((pSH4_ * sh_1.b2_c0_) + (pSH5_ * sh_1.b2_c1_)) + (pSH6_ * sh_1.b2_c2_)) + (pSH7_ * sh_1.b2_c3_)) + (pSH8_ * sh_1.b2_c4_)));
    if (degree == 2u) {
        let _e65 = colors;
        return _e65;
    }
    let fTmp0C = ((-2.285229f * z2_1) + 0.4570458f);
    let fTmp1B = (1.4453057f * z_1);
    let fC2_ = ((x_2 * fC1_) - (y_1 * fS1_));
    let fS2_ = ((x_2 * fS1_) + (y_1 * fC1_));
    let pSH12_ = (z_1 * ((1.8658817f * z2_1) - 1.119529f));
    let pSH13_ = (fTmp0C * x_2);
    let pSH11_ = (fTmp0C * y_1);
    let pSH14_ = (fTmp1B * fC1_);
    let pSH10_ = (fTmp1B * fS1_);
    let pSH15_ = (-0.5900436f * fC2_);
    let pSH9_ = (-0.5900436f * fS2_);
    let _e110 = colors;
    colors = (_e110 + (((((((pSH9_ * sh_1.b3_c0_) + (pSH10_ * sh_1.b3_c1_)) + (pSH11_ * sh_1.b3_c2_)) + (pSH12_ * sh_1.b3_c3_)) + (pSH13_ * sh_1.b3_c4_)) + (pSH14_ * sh_1.b3_c5_)) + (pSH15_ * sh_1.b3_c6_)));
    if (degree == 3u) {
        let _e114 = colors;
        return _e114;
    }
    let fTmp0D = (z_1 * ((-4.683326f * z2_1) + 2.0071397f));
    let fTmp1C = ((3.3116114f * z2_1) - 0.47308734f);
    let fTmp2B = (-1.7701308f * z_1);
    let fC3_ = ((x_2 * fC2_) - (y_1 * fS2_));
    let fS3_ = ((x_2 * fS2_) + (y_1 * fC2_));
    let pSH20_ = (((1.9843135f * z_1) * pSH12_) - (1.0062306f * pSH6_));
    let pSH21_ = (fTmp0D * x_2);
    let pSH19_ = (fTmp0D * y_1);
    let pSH22_ = (fTmp1C * fC1_);
    let pSH18_ = (fTmp1C * fS1_);
    let pSH23_ = (fTmp2B * fC2_);
    let pSH17_ = (fTmp2B * fS2_);
    let pSH24_ = (0.6258357f * fC3_);
    let pSH16_ = (0.6258357f * fS3_);
    let _e173 = colors;
    colors = (_e173 + (((((((((pSH16_ * sh_1.b4_c0_) + (pSH17_ * sh_1.b4_c1_)) + (pSH18_ * sh_1.b4_c2_)) + (pSH19_ * sh_1.b4_c3_)) + (pSH20_ * sh_1.b4_c4_)) + (pSH21_ * sh_1.b4_c5_)) + (pSH22_ * sh_1.b4_c6_)) + (pSH23_ * sh_1.b4_c7_)) + (pSH24_ * sh_1.b4_c8_)));
    let _e175 = colors;
    return _e175;
}

fn num_sh_coeffs(degree_1: u32) -> u32 {
    return ((degree_1 + 1u) * (degree_1 + 1u));
}

fn read_coeffs(base_id_1: ptr<function, u32>) -> vec3<f32> {
    let _e2 = (*base_id_1);
    let _e4 = coeffs[_e2];
    let _e5 = as_vec(_e4);
    let _e7 = (*base_id_1);
    (*base_id_1) = (_e7 + 1u);
    return _e5;
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {
    var base_id: u32;
    var sh: ShCoeffs = ShCoeffs();
    var color: vec3<f32>;

    let compact_gid = gid.x;
    let _e5 = atomicLoad((&uniforms.num_visible));
    if (compact_gid >= _e5) {
        return;
    }
    let global_gid = global_from_compact_gid[compact_gid];
    let _e12 = means[global_gid];
    let _e13 = as_vec(_e12);
    let _e16 = log_scales[global_gid];
    let _e17 = as_vec(_e16);
    let scale_2 = exp(_e17);
    let _e21 = quats[global_gid];
    let quat_2 = normalize(_e21);
    let _e25 = raw_opacities[global_gid];
    let _e26 = sigmoid(_e25);
    let viewmat_1 = uniforms.viewmat;
    let R_1 = mat3x3<f32>(viewmat_1[0].xyz, viewmat_1[1].xyz, viewmat_1[2].xyz);
    let mean_c_2 = ((R_1 * _e13) + viewmat_1[3].xyz);
    let _e41 = calc_cov3d(scale_2, quat_2);
    let _e44 = uniforms.focal;
    let _e47 = uniforms.img_size;
    let _e50 = uniforms.pixel_center;
    let _e51 = calc_cov2d(_e41, mean_c_2, _e44, _e47, _e50, viewmat_1);
    let _e52 = inverse(_e51);
    let rz_1 = (1f / mean_c_2.z);
    let _e58 = uniforms.focal;
    let _e64 = uniforms.pixel_center;
    let mean2d = (((_e58 * mean_c_2.xy) * rz_1) + _e64);
    let sh_degree = uniforms.sh_degree;
    let _e69 = num_sh_coeffs(sh_degree);
    base_id = (u32(global_gid) * _e69);
    let _e75 = read_coeffs((&base_id));
    sh.b0_c0_ = _e75;
    if (sh_degree >= 1u) {
        let _e79 = read_coeffs((&base_id));
        sh.b1_c0_ = _e79;
        let _e81 = read_coeffs((&base_id));
        sh.b1_c1_ = _e81;
        let _e83 = read_coeffs((&base_id));
        sh.b1_c2_ = _e83;
        if (sh_degree >= 2u) {
            let _e87 = read_coeffs((&base_id));
            sh.b2_c0_ = _e87;
            let _e89 = read_coeffs((&base_id));
            sh.b2_c1_ = _e89;
            let _e91 = read_coeffs((&base_id));
            sh.b2_c2_ = _e91;
            let _e93 = read_coeffs((&base_id));
            sh.b2_c3_ = _e93;
            let _e95 = read_coeffs((&base_id));
            sh.b2_c4_ = _e95;
            if (sh_degree >= 3u) {
                let _e99 = read_coeffs((&base_id));
                sh.b3_c0_ = _e99;
                let _e101 = read_coeffs((&base_id));
                sh.b3_c1_ = _e101;
                let _e103 = read_coeffs((&base_id));
                sh.b3_c2_ = _e103;
                let _e105 = read_coeffs((&base_id));
                sh.b3_c3_ = _e105;
                let _e107 = read_coeffs((&base_id));
                sh.b3_c4_ = _e107;
                let _e109 = read_coeffs((&base_id));
                sh.b3_c5_ = _e109;
                let _e111 = read_coeffs((&base_id));
                sh.b3_c6_ = _e111;
                if (sh_degree >= 4u) {
                    let _e115 = read_coeffs((&base_id));
                    sh.b4_c0_ = _e115;
                    let _e117 = read_coeffs((&base_id));
                    sh.b4_c1_ = _e117;
                    let _e119 = read_coeffs((&base_id));
                    sh.b4_c2_ = _e119;
                    let _e121 = read_coeffs((&base_id));
                    sh.b4_c3_ = _e121;
                    let _e123 = read_coeffs((&base_id));
                    sh.b4_c4_ = _e123;
                    let _e125 = read_coeffs((&base_id));
                    sh.b4_c5_ = _e125;
                    let _e127 = read_coeffs((&base_id));
                    sh.b4_c6_ = _e127;
                    let _e129 = read_coeffs((&base_id));
                    sh.b4_c7_ = _e129;
                    let _e131 = read_coeffs((&base_id));
                    sh.b4_c8_ = _e131;
                }
            }
        }
    }
    let _e134 = uniforms.camera_position;
    let viewdir_1 = normalize((_e13 - _e134.xyz));
    let _e138 = sh;
    let _e139 = sh_coeffs_to_color(sh_degree, viewdir_1, _e138);
    color = (_e139 + vec3(0.5f));
    let _e153 = color;
    let _e155 = create_projected_splat(mean2d, vec3<f32>(_e52[0].x, _e52[0].y, _e52[1].y), vec4<f32>(_e153, _e26));
    projected[compact_gid] = _e155;
    return;
}

