// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-render/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/project_forward.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct RenderUniforms {
    viewmat: mat4x4<f32>,
    focal: vec2<f32>,
    img_size: vec2<u32>,
    tile_bounds: vec2<u32>,
    pixel_center: vec2<f32>,
    camera_position: vec4<f32>,
    sh_degree: u32,
    num_visible: atomic<u32>,
    total_splats: u32,
    max_intersects: u32,
    background: vec4<f32>,
}

struct PackedVec3 {
    x: f32,
    y: f32,
    z: f32,
}

const COV_BLUR: f32 = 0.3f;

@group(0) @binding(0) 
var<storage, read_write> uniforms: RenderUniforms;
@group(0) @binding(1) 
var<storage> means: array<PackedVec3>;
@group(0) @binding(2) 
var<storage> quats: array<vec4<f32>>;
@group(0) @binding(3) 
var<storage> log_scales: array<PackedVec3>;
@group(0) @binding(4) 
var<storage> raw_opacities: array<f32>;
@group(0) @binding(5) 
var<storage, read_write> global_from_compact_gid: array<u32>;
@group(0) @binding(6) 
var<storage, read_write> depths: array<f32>;

fn sigmoid(x: f32) -> f32 {
    return (1f / (1f + exp(-(x))));
}

fn quat_to_mat(quat_1: vec4<f32>) -> mat3x3<f32> {
    let w = quat_1.x;
    let x_1 = quat_1.y;
    let y = quat_1.z;
    let z = quat_1.w;
    let x2_ = (x_1 * x_1);
    let y2_ = (y * y);
    let z2_ = (z * z);
    let xy = (x_1 * y);
    let xz = (x_1 * z);
    let yz = (y * z);
    let wx = (w * x_1);
    let wy = (w * y);
    let wz = (w * z);
    return mat3x3<f32>(vec3<f32>((1f - (2f * (y2_ + z2_))), (2f * (xy + wz)), (2f * (xz - wy))), vec3<f32>((2f * (xy - wz)), (1f - (2f * (x2_ + z2_))), (2f * (yz + wx))), vec3<f32>((2f * (xz + wy)), (2f * (yz - wx)), (1f - (2f * (x2_ + y2_)))));
}

fn scale_to_mat(scale: vec3<f32>) -> mat3x3<f32> {
    return mat3x3<f32>(vec3<f32>(scale.x, 0f, 0f), vec3<f32>(0f, scale.y, 0f), vec3<f32>(0f, 0f, scale.z));
}

fn calc_cov3d(scale_1: vec3<f32>, quat_2: vec4<f32>) -> mat3x3<f32> {
    let _e1 = quat_to_mat(quat_2);
    let _e3 = scale_to_mat(scale_1);
    let M = (_e1 * _e3);
    return (M * transpose(M));
}

fn calc_cam_J(mean_c: vec3<f32>, focal: vec2<f32>, img_size: vec2<u32>, pixel_center: vec2<f32>) -> mat3x2<f32> {
    let lims_pos = (((1.15f * vec2<f32>(img_size.xy)) - pixel_center) / focal);
    let lims_neg = (((-0.15f * vec2<f32>(img_size.xy)) - pixel_center) / focal);
    let rz = (1f / mean_c.z);
    let uv_clipped = clamp((mean_c.xy * rz), lims_neg, lims_pos);
    let duv_dxy = (focal * rz);
    let J = mat3x2<f32>(vec2<f32>(duv_dxy.x, 0f), vec2<f32>(0f, duv_dxy.y), (-(duv_dxy) * uv_clipped));
    return J;
}

fn calc_cov2d(cov3d: mat3x3<f32>, mean_c_1: vec3<f32>, focal_1: vec2<f32>, img_size_1: vec2<u32>, pixel_center_1: vec2<f32>, viewmat: mat4x4<f32>) -> mat2x2<f32> {
    var cov2d: mat2x2<f32>;

    let R = mat3x3<f32>(viewmat[0].xyz, viewmat[1].xyz, viewmat[2].xyz);
    let covar_cam = ((R * cov3d) * transpose(R));
    let _e16 = calc_cam_J(mean_c_1, focal_1, img_size_1, pixel_center_1);
    cov2d = ((_e16 * covar_cam) * transpose(_e16));
    let _e24 = cov2d[0][0];
    cov2d[0][0] = (_e24 + COV_BLUR);
    let _e29 = cov2d[1][1];
    cov2d[1][1] = (_e29 + COV_BLUR);
    let _e31 = cov2d;
    return _e31;
}

fn compute_bbox_extent(cov2d_1: mat2x2<f32>, power_threshold: f32) -> vec2<f32> {
    return vec2<f32>(sqrt(((2f * power_threshold) * cov2d_1[0].x)), sqrt(((2f * power_threshold) * cov2d_1[1].y)));
}

fn as_vec(packed: PackedVec3) -> vec3<f32> {
    return vec3<f32>(packed.x, packed.y, packed.z);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(global_invocation_id) global_id: vec3<u32>) {
    var quat: vec4<f32>;

    let global_gid = global_id.x;
    let _e4 = uniforms.total_splats;
    if (global_gid >= _e4) {
        return;
    }
    let _e8 = means[global_gid];
    let _e9 = as_vec(_e8);
    let img_size_2 = uniforms.img_size;
    let viewmat_1 = uniforms.viewmat;
    let R_1 = mat3x3<f32>(viewmat_1[0].xyz, viewmat_1[1].xyz, viewmat_1[2].xyz);
    let mean_c_2 = ((R_1 * _e9) + viewmat_1[3].xyz);
    if ((mean_c_2.z < 0.01f) || (mean_c_2.z > 10000000000f)) {
        return;
    }
    let _e36 = log_scales[global_gid];
    let _e37 = as_vec(_e36);
    let scale_2 = exp(_e37);
    let _e41 = quats[global_gid];
    quat = _e41;
    let _e43 = quat;
    let _e44 = quat;
    let quat_norm_sqr = dot(_e43, _e44);
    if (quat_norm_sqr < 0.000001f) {
        return;
    }
    let _e49 = quat;
    quat = (_e49 * inverseSqrt(quat_norm_sqr));
    let _e51 = quat;
    let _e52 = calc_cov3d(scale_2, _e51);
    let _e55 = uniforms.focal;
    let _e58 = uniforms.img_size;
    let _e61 = uniforms.pixel_center;
    let _e62 = calc_cov2d(_e52, mean_c_2, _e55, _e58, _e61, viewmat_1);
    if (abs(determinant(_e62)) < 0.000000000000000000000001f) {
        return;
    }
    let _e69 = uniforms.focal;
    let _e78 = uniforms.pixel_center;
    let mean2d = (((_e69 * mean_c_2.xy) * (1f / mean_c_2.z)) + _e78);
    let _e82 = raw_opacities[global_gid];
    let _e83 = sigmoid(_e82);
    if (_e83 < 0.003921569f) {
        return;
    }
    let _e89 = compute_bbox_extent(_e62, log((255f * _e83)));
    if ((_e89.x < 0f) || (_e89.y < 0f)) {
        return;
    }
    let _e108 = uniforms.img_size.x;
    let _e124 = uniforms.img_size.y;
    if (((((mean2d.x + _e89.x) <= 0f) || ((mean2d.x - _e89.x) >= f32(_e108))) || ((mean2d.y + _e89.y) <= 0f)) || ((mean2d.y - _e89.y) >= f32(_e124))) {
        return;
    }
    let _e131 = atomicAdd((&uniforms.num_visible), 1u);
    global_from_compact_gid[_e131] = global_gid;
    depths[_e131] = mean_c_2.z;
    return;
}

