// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-render/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/rasterize.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct RenderUniforms {
    viewmat: mat4x4<f32>,
    focal: vec2<f32>,
    img_size: vec2<u32>,
    tile_bounds: vec2<u32>,
    pixel_center: vec2<f32>,
    camera_position: vec4<f32>,
    sh_degree: u32,
    num_visible: u32,
    total_splats: u32,
    max_intersects: u32,
    background: vec4<f32>,
}

struct ProjectedSplat {
    xy_x: f32,
    xy_y: f32,
    conic_x: f32,
    conic_y: f32,
    conic_z: f32,
    color_r: f32,
    color_g: f32,
    color_b: f32,
    color_a: f32,
}

const TILE_WIDTH: u32 = 16u;
const TILE_SIZE: u32 = 256u;

@group(0) @binding(0) 
var<storage> uniforms: RenderUniforms;
@group(0) @binding(1) 
var<storage> compact_gid_from_isect: array<u32>;
@group(0) @binding(2) 
var<storage> tile_offsets: array<u32>;
@group(0) @binding(3) 
var<storage> projected: array<ProjectedSplat>;
@group(0) @binding(4) 
var<storage, read_write> out_img: array<u32>;
var<workgroup> range_uniform: vec2<u32>;
var<workgroup> local_batch: array<ProjectedSplat, 256>;

fn compact_bits_16(v: u32) -> u32 {
    var x: u32;

    x = (v & 1431655765u);
    let _e4 = x;
    let _e5 = x;
    x = ((_e4 | (_e5 >> 1u)) & 858993459u);
    let _e11 = x;
    let _e12 = x;
    x = ((_e11 | (_e12 >> 2u)) & 252645135u);
    let _e18 = x;
    let _e19 = x;
    x = ((_e18 | (_e19 >> 4u)) & 16711935u);
    let _e25 = x;
    let _e26 = x;
    x = ((_e25 | (_e26 >> 8u)) & 65535u);
    let _e32 = x;
    return _e32;
}

fn decode_morton_2d(morton: u32) -> vec2<u32> {
    let _e1 = compact_bits_16(morton);
    let _e4 = compact_bits_16((morton >> 1u));
    return vec2<u32>(_e1, _e4);
}

fn map_1d_to_2d(id: u32, tiles_per_row: u32) -> vec2<u32> {
    let tile_id = (id / TILE_SIZE);
    let within_tile_id = (id % TILE_SIZE);
    let tile_x = (tile_id % tiles_per_row);
    let tile_y = (tile_id / tiles_per_row);
    let _e13 = decode_morton_2d(within_tile_id);
    return (vec2<u32>((tile_x * TILE_WIDTH), (tile_y * TILE_WIDTH)) + _e13);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(global_invocation_id) global_id: vec3<u32>, @builtin(local_invocation_index) local_idx: u32) {
    var T: f32 = 1f;
    var pix_out: vec3<f32> = vec3(0f);
    var done: bool;
    var batch_start: u32;
    var t: u32;

    let _e8 = uniforms.tile_bounds.x;
    let _e9 = map_1d_to_2d(global_id.x, _e8);
    let _e15 = uniforms.img_size.x;
    let pix_id = (_e9.x + (_e9.y * _e15));
    let pixel_coord = (vec2<f32>(_e9) + vec2(0.5f));
    let tile_loc = vec2<u32>((_e9.x / TILE_WIDTH), (_e9.y / TILE_WIDTH));
    let _e34 = uniforms.tile_bounds.x;
    let tile_id_1 = (tile_loc.x + (tile_loc.y * _e34));
    let _e41 = uniforms.img_size.x;
    let _e47 = uniforms.img_size.y;
    let inside = ((_e9.x < _e41) && (_e9.y < _e47));
    let _e54 = tile_offsets[(tile_id_1 * 2u)];
    let _e61 = tile_offsets[((tile_id_1 * 2u) + 1u)];
    range_uniform = vec2<u32>(_e54, _e61);
    let _e65 = workgroupUniformLoad((&range_uniform));
    done = !(inside);
    batch_start = _e65.x;
    loop {
        let _e70 = batch_start;
        if (_e70 < _e65.y) {
        } else {
            break;
        }
        {
            let _e75 = batch_start;
            let remaining = min(TILE_SIZE, (_e65.y - _e75));
            let _e79 = batch_start;
            let load_isect_id = (_e79 + local_idx);
            let compact_gid = compact_gid_from_isect[load_isect_id];
            workgroupBarrier();
            if (local_idx < remaining) {
                let _e89 = projected[compact_gid];
                local_batch[local_idx] = _e89;
            }
            workgroupBarrier();
            t = 0u;
            loop {
                let _e92 = done;
                let _e94 = t;
                if (!(_e92) && (_e94 < remaining)) {
                } else {
                    break;
                }
                {
                    let _e98 = t;
                    let proj = local_batch[_e98];
                    let xy = vec2<f32>(proj.xy_x, proj.xy_y);
                    let conic = vec3<f32>(proj.conic_x, proj.conic_y, proj.conic_z);
                    let color = vec4<f32>(proj.color_r, proj.color_g, proj.color_b, proj.color_a);
                    let delta = (xy - pixel_coord);
                    let sigma = ((0.5f * (((conic.x * delta.x) * delta.x) + ((conic.z * delta.y) * delta.y))) + ((conic.y * delta.x) * delta.y));
                    let alpha = min(0.999f, (color.w * exp(-(sigma))));
                    if ((sigma >= 0f) && (alpha >= 0.003921569f)) {
                        let _e145 = T;
                        let next_T = (_e145 * (1f - alpha));
                        if (next_T <= 0.0001f) {
                            done = true;
                            break;
                        }
                        let _e152 = T;
                        let vis = (alpha * _e152);
                        let _e160 = pix_out;
                        pix_out = (_e160 + (max(color.xyz, vec3(0f)) * vis));
                        T = next_T;
                    }
                }
                continuing {
                    let _e163 = t;
                    t = (_e163 + 1u);
                }
            }
        }
        continuing {
            let _e166 = batch_start;
            batch_start = (_e166 + TILE_SIZE);
        }
    }
    if inside {
        let _e168 = pix_out;
        let _e169 = T;
        let _e172 = uniforms.background;
        let _e176 = T;
        let final_color = vec4<f32>((_e168 + (_e169 * _e172.xyz)), (1f - _e176));
        let colors_u = vec4<u32>(clamp((final_color * 255f), vec4(0f), vec4(255f)));
        let packed = (((colors_u.x | (colors_u.y << 8u)) | (colors_u.z << 16u)) | (colors_u.w << 24u));
        out_img[pix_id] = packed;
        return;
    } else {
        return;
    }
}

