// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-render-bwd/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/rasterize_backwards.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct RenderUniforms {
    viewmat: mat4x4<f32>,
    focal: vec2<f32>,
    img_size: vec2<u32>,
    tile_bounds: vec2<u32>,
    pixel_center: vec2<f32>,
    camera_position: vec4<f32>,
    sh_degree: u32,
    num_visible: u32,
    total_splats: u32,
    max_intersects: u32,
    background: vec4<f32>,
}

struct ProjectedSplat {
    xy_x: f32,
    xy_y: f32,
    conic_x: f32,
    conic_y: f32,
    conic_z: f32,
    color_r: f32,
    color_g: f32,
    color_b: f32,
    color_a: f32,
}

const TILE_WIDTH: u32 = 16u;
const TILE_SIZE: u32 = 256u;
const THREAD_COUNT: u32 = 64u;
const PIXELS_PER_THREAD: u32 = 4u;

@group(0) @binding(0) 
var<storage> uniforms: RenderUniforms;
@group(0) @binding(1) 
var<storage> compact_gid_from_isect: array<u32>;
@group(0) @binding(2) 
var<storage> global_from_compact_gid: array<u32>;
@group(0) @binding(3) 
var<storage> tile_offsets: array<u32>;
@group(0) @binding(4) 
var<storage> projected: array<ProjectedSplat>;
@group(0) @binding(5) 
var<storage> output: array<vec4<f32>>;
@group(0) @binding(6) 
var<storage> v_output: array<vec4<f32>>;
@group(0) @binding(7) 
var<storage, read_write> v_splats: array<atomic<u32>>;
@group(0) @binding(8) 
var<storage, read_write> v_opacs: array<atomic<u32>>;
@group(0) @binding(9) 
var<storage, read_write> v_refines: array<atomic<u32>>;
var<workgroup> local_batch: array<ProjectedSplat, 64>;
var<workgroup> load_gid: array<u32, 64>;
var<workgroup> range_uniform: vec2<u32>;

fn compact_bits_16(v: u32) -> u32 {
    var x: u32;

    x = (v & 1431655765u);
    let _e4 = x;
    let _e5 = x;
    x = ((_e4 | (_e5 >> 1u)) & 858993459u);
    let _e11 = x;
    let _e12 = x;
    x = ((_e11 | (_e12 >> 2u)) & 252645135u);
    let _e18 = x;
    let _e19 = x;
    x = ((_e18 | (_e19 >> 4u)) & 16711935u);
    let _e25 = x;
    let _e26 = x;
    x = ((_e25 | (_e26 >> 8u)) & 65535u);
    let _e32 = x;
    return _e32;
}

fn decode_morton_2d(morton: u32) -> vec2<u32> {
    let _e1 = compact_bits_16(morton);
    let _e4 = compact_bits_16((morton >> 1u));
    return vec2<u32>(_e1, _e4);
}

fn map_1d_to_2d(id: u32, tiles_per_row: u32) -> vec2<u32> {
    let tile_id = (id / TILE_SIZE);
    let within_tile_id = (id % TILE_SIZE);
    let tile_x = (tile_id % tiles_per_row);
    let tile_y = (tile_id / tiles_per_row);
    let _e13 = decode_morton_2d(within_tile_id);
    return (vec2<u32>((tile_x * TILE_WIDTH), (tile_y * TILE_WIDTH)) + _e13);
}

fn add_bitcast(cur: u32, add: f32) -> u32 {
    return bitcast<u32>((bitcast<f32>(cur) + add));
}

fn write_grads_atomic(id_1: u32, grads: f32) {
    var old_value: u32;

    let _e3 = atomicLoad((&v_splats[id_1]));
    old_value = _e3;
    loop {
        let _e7 = old_value;
        let _e8 = old_value;
        let _e10 = add_bitcast(_e8, grads);
        let _e11 = atomicCompareExchangeWeak((&v_splats[id_1]), _e7, _e10);
        if _e11.exchanged {
            break;
        } else {
            old_value = _e11.old_value;
        }
    }
    return;
}

fn write_refine_atomic(id_2: u32, grads_1: f32) {
    var old_value_1: u32;

    let _e3 = atomicLoad((&v_refines[id_2]));
    old_value_1 = _e3;
    loop {
        let _e7 = old_value_1;
        let _e8 = old_value_1;
        let _e10 = add_bitcast(_e8, grads_1);
        let _e11 = atomicCompareExchangeWeak((&v_refines[id_2]), _e7, _e10);
        if _e11.exchanged {
            break;
        } else {
            old_value_1 = _e11.old_value;
        }
    }
    return;
}

fn write_opac_atomic(id_3: u32, grads_2: f32) {
    var old_value_2: u32;

    let _e3 = atomicLoad((&v_opacs[id_3]));
    old_value_2 = _e3;
    loop {
        let _e7 = old_value_2;
        let _e8 = old_value_2;
        let _e10 = add_bitcast(_e8, grads_2);
        let _e11 = atomicCompareExchangeWeak((&v_opacs[id_3]), _e7, _e10);
        if _e11.exchanged {
            break;
        } else {
            old_value_2 = _e11.old_value;
        }
    }
    return;
}

@compute @workgroup_size(64, 1, 1) 
fn main(@builtin(global_invocation_id) global_id: vec3<u32>, @builtin(local_invocation_index) local_idx: u32, @builtin(subgroup_invocation_id) subgroup_invocation_id: u32) {
    var pix_locs: array<vec2<u32>, 4> = array<vec2<u32>, 4>();
    var pix_ids: array<u32, 4> = array<u32, 4>();
    var v_outs: array<vec4<f32>, 4> = array<vec4<f32>, 4>();
    var pix_outs: array<vec4<f32>, 4> = array<vec4<f32>, 4>();
    var dones: array<bool, 4> = array<bool, 4>();
    var rgb_pixel_finals: array<vec3<f32>, 4> = array<vec3<f32>, 4>();
    var i: u32 = 0u;
    var batch_start: u32;
    var t: u32;
    var v_xy_thread: vec2<f32>;
    var v_conic_thread: vec3<f32>;
    var v_rgb_thread: vec3<f32>;
    var v_alpha_thread: f32;
    var v_refine_thread: f32;
    var hasGrad: bool;
    var i_1: u32;

    loop {
        let _e7 = i;
        if (_e7 < PIXELS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e14 = i;
            let thread_id = ((global_id.x * PIXELS_PER_THREAD) + _e14);
            let _e17 = i;
            let _e22 = uniforms.tile_bounds.x;
            let _e23 = map_1d_to_2d(thread_id, _e22);
            pix_locs[_e17] = _e23;
            let _e24 = i;
            let _e27 = pix_locs[_e24].x;
            let _e28 = i;
            let _e31 = pix_locs[_e28].y;
            let _e35 = uniforms.img_size.x;
            let pix_id = (_e27 + (_e31 * _e35));
            let _e39 = i;
            pix_ids[_e39] = pix_id;
            let _e41 = i;
            let _e44 = pix_locs[_e41].x;
            let _e48 = uniforms.img_size.x;
            let _e50 = i;
            let _e53 = pix_locs[_e50].y;
            let _e57 = uniforms.img_size.y;
            if ((_e44 < _e48) && (_e53 < _e57)) {
                let final_color = output[pix_id];
                let v_out = v_output[pix_id];
                let T_final = (1f - final_color.w);
                let _e70 = i;
                let _e75 = uniforms.background;
                rgb_pixel_finals[_e70] = (final_color.xyz - (T_final * _e75.xyz));
                let _e80 = i;
                let _e86 = uniforms.background;
                v_outs[_e80] = vec4<f32>(v_out.xyz, ((v_out.w - dot(_e86.xyz, v_out.xyz)) * T_final));
                let _e94 = i;
                dones[_e94] = false;
            } else {
                let _e97 = i;
                dones[_e97] = true;
            }
            let _e101 = i;
            pix_outs[_e101] = vec4<f32>(0f, 0f, 0f, 1f);
        }
        continuing {
            let _e109 = i;
            i = (_e109 + 1u);
        }
    }
    let _e113 = pix_locs[0].x;
    let _e118 = pix_locs[0].y;
    let tile_loc = vec2<u32>((_e113 / TILE_WIDTH), (_e118 / TILE_WIDTH));
    let _e127 = uniforms.tile_bounds.x;
    let tile_id_1 = (tile_loc.x + (tile_loc.y * _e127));
    let _e134 = tile_offsets[(tile_id_1 * 2u)];
    let _e141 = tile_offsets[((tile_id_1 * 2u) + 1u)];
    range_uniform = vec2<u32>(_e134, _e141);
    let _e145 = workgroupUniformLoad((&range_uniform));
    batch_start = _e145.x;
    loop {
        let _e148 = batch_start;
        if (_e148 < _e145.y) {
        } else {
            break;
        }
        {
            let _e153 = batch_start;
            let remaining = min(THREAD_COUNT, (_e145.y - _e153));
            let _e157 = batch_start;
            let load_isect_id = (_e157 + local_idx);
            let compact_gid = compact_gid_from_isect[load_isect_id];
            workgroupBarrier();
            if (local_idx < remaining) {
                let _e167 = global_from_compact_gid[compact_gid];
                load_gid[local_idx] = _e167;
                let _e172 = projected[compact_gid];
                local_batch[local_idx] = _e172;
            }
            workgroupBarrier();
            t = 0u;
            loop {
                let _e175 = t;
                if (_e175 < remaining) {
                } else {
                    break;
                }
                {
                    v_xy_thread = vec2(0f);
                    v_conic_thread = vec3(0f);
                    v_rgb_thread = vec3(0f);
                    v_alpha_thread = 0f;
                    v_refine_thread = 0f;
                    hasGrad = false;
                    let _e193 = t;
                    let proj = local_batch[_e193];
                    let xy = vec2<f32>(proj.xy_x, proj.xy_y);
                    let conic = vec3<f32>(proj.conic_x, proj.conic_y, proj.conic_z);
                    let color = vec4<f32>(proj.color_r, proj.color_g, proj.color_b, proj.color_a);
                    let clamped_rgb = max(color.xyz, vec3(0f));
                    i_1 = 0u;
                    loop {
                        let _e214 = i_1;
                        if (_e214 < PIXELS_PER_THREAD) {
                        } else {
                            break;
                        }
                        {
                            let _e217 = i_1;
                            let _e219 = dones[_e217];
                            if _e219 {
                                continue;
                            }
                            let _e220 = i_1;
                            let _e222 = pix_locs[_e220];
                            let pixel_coord = (vec2<f32>(_e222) + vec2(0.5f));
                            let delta = (xy - pixel_coord);
                            let sigma = ((0.5f * (((conic.x * delta.x) * delta.x) + ((conic.z * delta.y) * delta.y))) + ((conic.y * delta.x) * delta.y));
                            let gaussian = exp(-(sigma));
                            let alpha = min(0.999f, (color.w * gaussian));
                            if ((sigma < 0f) || (alpha < 0.003921569f)) {
                                continue;
                            }
                            let _e258 = i_1;
                            let _e261 = pix_outs[_e258].w;
                            let next_T = (_e261 * (1f - alpha));
                            if (next_T <= 0.0001f) {
                                let _e267 = i_1;
                                dones[_e267] = true;
                                continue;
                            }
                            let _e270 = i_1;
                            let _e273 = pix_outs[_e270].w;
                            let vis = (alpha * _e273);
                            let _e277 = i_1;
                            let _e279 = v_outs[_e277];
                            let v_rgb_local = select(vec3(0f), (vis * _e279.xyz), (color.xyz >= vec3(0f)));
                            let _e287 = v_rgb_thread;
                            v_rgb_thread = (_e287 + v_rgb_local);
                            let _e289 = i_1;
                            let _e291 = i_1;
                            let _e293 = pix_outs[_e291];
                            let _e297 = i_1;
                            let _e300 = pix_outs[_e297].w;
                            pix_outs[_e289] = vec4<f32>((_e293.xyz + (vis * clamped_rgb)), _e300);
                            if ((color.w * gaussian) <= 0.999f) {
                                let ra = (1f / (1f - alpha));
                                let _e310 = i_1;
                                let _e313 = pix_outs[_e310].w;
                                let _e315 = i_1;
                                let _e317 = pix_outs[_e315];
                                let _e319 = i_1;
                                let _e321 = rgb_pixel_finals[_e319];
                                let _e325 = i_1;
                                let _e327 = v_outs[_e325];
                                let _e330 = i_1;
                                let _e333 = v_outs[_e330].w;
                                let v_alpha = (dot(((_e313 * clamped_rgb) + ((_e317.xyz - _e321) * ra)), _e327.xyz) + (_e333 * ra));
                                let v_sigma = (-(alpha) * v_alpha);
                                let _e355 = v_conic_thread;
                                v_conic_thread = (_e355 + vec3<f32>((((0.5f * v_sigma) * delta.x) * delta.x), ((v_sigma * delta.x) * delta.y), (((0.5f * v_sigma) * delta.y) * delta.y)));
                                let v_xy_local = (v_sigma * vec2<f32>(((conic.x * delta.x) + (conic.y * delta.y)), ((conic.y * delta.x) + (conic.z * delta.y))));
                                let _e373 = v_xy_thread;
                                v_xy_thread = (_e373 + v_xy_local);
                                let _e380 = v_alpha_thread;
                                v_alpha_thread = (_e380 + ((alpha * (1f - color.w)) * v_alpha));
                                let _e386 = uniforms.img_size.x;
                                let _e394 = uniforms.img_size.y;
                                let _e399 = v_refine_thread;
                                v_refine_thread = (_e399 + (abs((v_xy_local.x * f32(_e386))) + abs((v_xy_local.y * f32(_e394)))));
                                let _e403 = uniforms.img_size;
                                let refine_scale = vec2<f32>(_e403);
                            }
                            hasGrad = true;
                            let _e406 = i_1;
                            pix_outs[_e406].w = next_T;
                        }
                        continuing {
                            let _e410 = i_1;
                            i_1 = (_e410 + 1u);
                        }
                    }
                    let _e412 = hasGrad;
                    let _e413 = subgroupAny(_e412);
                    let doAdd = (subgroup_invocation_id == 0u);
                    if _e413 {
                        let _e417 = v_xy_thread;
                        let _e418 = subgroupAdd(_e417);
                        let _e419 = v_conic_thread;
                        let _e420 = subgroupAdd(_e419);
                        let _e421 = v_rgb_thread;
                        let _e422 = subgroupAdd(_e421);
                        let _e423 = v_alpha_thread;
                        let _e424 = subgroupAdd(_e423);
                        let _e425 = v_refine_thread;
                        let _e426 = subgroupAdd(_e425);
                        if doAdd {
                            let _e428 = t;
                            let global_gid = load_gid[_e428];
                            write_grads_atomic(((global_gid * 8u) + 0u), _e418.x);
                            write_grads_atomic(((global_gid * 8u) + 1u), _e418.y);
                            write_grads_atomic(((global_gid * 8u) + 2u), _e420.x);
                            write_grads_atomic(((global_gid * 8u) + 3u), _e420.y);
                            write_grads_atomic(((global_gid * 8u) + 4u), _e420.z);
                            write_grads_atomic(((global_gid * 8u) + 5u), _e422.x);
                            write_grads_atomic(((global_gid * 8u) + 6u), _e422.y);
                            write_grads_atomic(((global_gid * 8u) + 7u), _e422.z);
                            write_opac_atomic(global_gid, _e424);
                            write_refine_atomic(global_gid, _e426);
                        }
                    }
                }
                continuing {
                    let _e472 = t;
                    t = (_e472 + 1u);
                }
            }
        }
        continuing {
            let _e475 = batch_start;
            batch_start = (_e475 + THREAD_COUNT);
        }
    }
    return;
}

