// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-sort/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/sort_count.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct Uniforms {
    shift: u32,
}

const WG: u32 = 256u;
const BIN_COUNT: u32 = 16u;
const ELEMENTS_PER_THREAD: u32 = 4u;
const BLOCK_SIZE: u32 = 1024u;

@group(0) @binding(0) 
var<storage> config: Uniforms;
@group(0) @binding(1) 
var<storage> num_keys_arr: array<u32>;
@group(0) @binding(2) 
var<storage> src: array<u32>;
@group(0) @binding(3) 
var<storage, read_write> counts: array<u32>;
var<workgroup> histogram: array<atomic<u32>, 16>;

fn div_ceil(a: u32, b: u32) -> u32 {
    return (((a + b) - 1u) / b);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(local_invocation_id) local_id: vec3<u32>, @builtin(workgroup_id) gid: vec3<u32>) {
    var block_index: u32;
    var data_index: u32;
    var i: u32 = 0u;

    let num_keys = num_keys_arr[0];
    let _e5 = div_ceil(num_keys, BLOCK_SIZE);
    let group_id = gid.x;
    if (group_id >= _e5) {
        return;
    }
    if (local_id.x < BIN_COUNT) {
        atomicStore((&histogram[local_id.x]), 0u);
    }
    workgroupBarrier();
    let wg_block_start = (BLOCK_SIZE * group_id);
    block_index = (wg_block_start + local_id.x);
    let shift_bit = config.shift;
    let _e25 = block_index;
    data_index = _e25;
    loop {
        let _e28 = i;
        if (_e28 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e31 = data_index;
            if (_e31 < num_keys) {
                let _e34 = data_index;
                let _e36 = src[_e34];
                let local_key = ((_e36 >> shift_bit) & 15u);
                let _e43 = atomicAdd((&histogram[local_key]), 1u);
            }
            let _e45 = data_index;
            data_index = (_e45 + WG);
        }
        continuing {
            let _e48 = i;
            i = (_e48 + 1u);
        }
    }
    let _e51 = block_index;
    block_index = (_e51 + BLOCK_SIZE);
    workgroupBarrier();
    if (local_id.x < BIN_COUNT) {
        let _e57 = div_ceil(num_keys, BLOCK_SIZE);
        let _e66 = atomicLoad((&histogram[local_id.x]));
        counts[((local_id.x * _e57) + group_id)] = _e66;
        return;
    } else {
        return;
    }
}

