// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-sort/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/sort_scatter.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

struct Uniforms {
    shift: u32,
}

const WG: u32 = 256u;
const BITS_PER_PASS: u32 = 4u;
const BIN_COUNT: u32 = 16u;
const ELEMENTS_PER_THREAD: u32 = 4u;
const BLOCK_SIZE: u32 = 1024u;

@group(0) @binding(0) 
var<storage> config: Uniforms;
@group(0) @binding(1) 
var<storage> num_keys_arr: array<u32>;
@group(0) @binding(2) 
var<storage> src: array<u32>;
@group(0) @binding(3) 
var<storage> values: array<u32>;
@group(0) @binding(4) 
var<storage> counts: array<u32>;
@group(0) @binding(5) 
var<storage, read_write> out: array<u32>;
@group(0) @binding(6) 
var<storage, read_write> out_values: array<u32>;
var<workgroup> lds_sums: array<u32, 256>;
var<workgroup> lds_scratch: array<u32, 256>;
var<workgroup> bin_offset_cache: array<u32, 256>;
var<workgroup> local_histogram: array<atomic<u32>, 16>;

fn div_ceil(a: u32, b: u32) -> u32 {
    return (((a + b) - 1u) / b);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(local_invocation_id) local_id: vec3<u32>, @builtin(workgroup_id) gid: vec3<u32>) {
    var data_index: u32;
    var i: u32 = 0u;
    var local_key: u32;
    var local_value: u32;
    var bit_shift: u32;
    var packed_histogram: u32;
    var sum: u32;
    var i_1: u32;
    var local_sum: u32;
    var histogram_local_sum: u32;
    var histogram_prefix_sum: u32;
    var i_2: u32;
    var local_offset: u32;

    let num_keys = num_keys_arr[0];
    let _e5 = div_ceil(num_keys, BLOCK_SIZE);
    let group_id = gid.x;
    if (group_id >= _e5) {
        return;
    }
    if (local_id.x < BIN_COUNT) {
        let _e21 = counts[((local_id.x * _e5) + group_id)];
        bin_offset_cache[local_id.x] = _e21;
    }
    workgroupBarrier();
    let wg_block_start = (BLOCK_SIZE * group_id);
    let block_index = (wg_block_start + local_id.x);
    data_index = block_index;
    loop {
        let _e28 = i;
        if (_e28 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            if (local_id.x < BIN_COUNT) {
                atomicStore((&local_histogram[local_id.x]), 0u);
            }
            local_key = 4294967295u;
            local_value = 0u;
            let _e42 = data_index;
            if (_e42 < num_keys) {
                let _e45 = data_index;
                let _e47 = src[_e45];
                local_key = _e47;
                let _e49 = data_index;
                let _e51 = values[_e49];
                local_value = _e51;
            }
            bit_shift = 0u;
            loop {
                let _e54 = bit_shift;
                if (_e54 < BITS_PER_PASS) {
                } else {
                    break;
                }
                {
                    let _e57 = local_key;
                    let _e60 = config.shift;
                    let key_index = ((_e57 >> _e60) & 15u);
                    let _e64 = bit_shift;
                    let bit_key = ((key_index >> _e64) & 3u);
                    packed_histogram = (1u << (bit_key * 8u));
                    let _e73 = packed_histogram;
                    sum = _e73;
                    let _e78 = sum;
                    lds_scratch[local_id.x] = _e78;
                    i_1 = 0u;
                    loop {
                        let _e81 = i_1;
                        if (_e81 < 8u) {
                        } else {
                            break;
                        }
                        {
                            workgroupBarrier();
                            let _e86 = i_1;
                            if (local_id.x >= (1u << _e86)) {
                                let _e92 = i_1;
                                let _e96 = lds_scratch[(local_id.x - (1u << _e92))];
                                let _e97 = sum;
                                sum = (_e97 + _e96);
                            }
                            workgroupBarrier();
                            let _e102 = sum;
                            lds_scratch[local_id.x] = _e102;
                        }
                        continuing {
                            let _e104 = i_1;
                            i_1 = (_e104 + 1u);
                        }
                    }
                    workgroupBarrier();
                    let _e108 = lds_scratch[255];
                    packed_histogram = _e108;
                    let _e109 = packed_histogram;
                    let _e112 = packed_histogram;
                    let _e116 = packed_histogram;
                    packed_histogram = (((_e109 << 8u) + (_e112 << 16u)) + (_e116 << 24u));
                    let _e120 = packed_histogram;
                    local_sum = _e120;
                    if (local_id.x > 0u) {
                        let _e130 = lds_scratch[(local_id.x - 1u)];
                        let _e131 = local_sum;
                        local_sum = (_e131 + _e130);
                    }
                    let _e133 = local_sum;
                    let key_offset = ((_e133 >> (bit_key * 8u)) & 255u);
                    let _e141 = local_key;
                    lds_sums[key_offset] = _e141;
                    workgroupBarrier();
                    let _e145 = lds_sums[local_id.x];
                    local_key = _e145;
                    workgroupBarrier();
                    let _e148 = local_value;
                    lds_sums[key_offset] = _e148;
                    workgroupBarrier();
                    let _e152 = lds_sums[local_id.x];
                    local_value = _e152;
                    workgroupBarrier();
                }
                continuing {
                    let _e154 = bit_shift;
                    bit_shift = (_e154 + 2u);
                }
            }
            let _e156 = local_key;
            let _e159 = config.shift;
            let key_index_1 = ((_e156 >> _e159) & 15u);
            let _e166 = atomicAdd((&local_histogram[key_index_1]), 1u);
            workgroupBarrier();
            histogram_local_sum = 0u;
            if (local_id.x < BIN_COUNT) {
                let _e175 = atomicLoad((&local_histogram[local_id.x]));
                histogram_local_sum = _e175;
            }
            let _e176 = histogram_local_sum;
            histogram_prefix_sum = _e176;
            if (local_id.x < BIN_COUNT) {
                let _e184 = histogram_prefix_sum;
                lds_scratch[local_id.x] = _e184;
            }
            i_2 = 0u;
            loop {
                let _e187 = i_2;
                if (_e187 < 4u) {
                } else {
                    break;
                }
                {
                    workgroupBarrier();
                    let _e192 = i_2;
                    if ((local_id.x >= (1u << _e192)) && (local_id.x < BIN_COUNT)) {
                        let _e202 = i_2;
                        let _e206 = lds_scratch[(local_id.x - (1u << _e202))];
                        let _e207 = histogram_prefix_sum;
                        histogram_prefix_sum = (_e207 + _e206);
                    }
                    workgroupBarrier();
                    if (local_id.x < BIN_COUNT) {
                        let _e215 = histogram_prefix_sum;
                        lds_scratch[local_id.x] = _e215;
                    }
                }
                continuing {
                    let _e217 = i_2;
                    i_2 = (_e217 + 1u);
                }
            }
            let global_offset = bin_offset_cache[key_index_1];
            workgroupBarrier();
            local_offset = local_id.x;
            if (key_index_1 > 0u) {
                let _e230 = lds_scratch[(key_index_1 - 1u)];
                let _e231 = local_offset;
                local_offset = (_e231 - _e230);
            }
            let _e233 = local_offset;
            let total_offset = (global_offset + _e233);
            if (total_offset < num_keys) {
                let _e238 = local_key;
                out[total_offset] = _e238;
                let _e241 = local_value;
                out_values[total_offset] = _e241;
            }
            if (local_id.x < BIN_COUNT) {
                let _e251 = atomicLoad((&local_histogram[local_id.x]));
                let _e252 = bin_offset_cache[local_id.x];
                bin_offset_cache[local_id.x] = (_e252 + _e251);
            }
            workgroupBarrier();
            let _e255 = data_index;
            data_index = (_e255 + WG);
        }
        continuing {
            let _e258 = i;
            i = (_e258 + 1u);
        }
    }
    return;
}

