// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-sort/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/sort_scan_add.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

const WG: u32 = 256u;
const BIN_COUNT: u32 = 16u;
const ELEMENTS_PER_THREAD: u32 = 4u;
const BLOCK_SIZE: u32 = 1024u;

@group(0) @binding(0) 
var<storage> num_keys_arr: array<u32>;
@group(0) @binding(1) 
var<storage> reduced: array<u32>;
@group(0) @binding(2) 
var<storage, read_write> counts: array<u32>;
var<workgroup> sums: array<u32, 256>;
var<workgroup> lds: array<array<u32, 256>, 4>;

fn div_ceil(a: u32, b: u32) -> u32 {
    return (((a + b) - 1u) / b);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(local_invocation_id) local_id: vec3<u32>, @builtin(workgroup_id) gid: vec3<u32>) {
    var i: u32 = 0u;
    var sum: u32 = 0u;
    var i_1: u32 = 0u;
    var i_2: u32 = 0u;
    var i_3: u32 = 0u;
    var i_4: u32 = 0u;

    let num_keys = num_keys_arr[0];
    let _e5 = div_ceil(num_keys, BLOCK_SIZE);
    let _e7 = div_ceil(_e5, BLOCK_SIZE);
    let num_reduce_wgs = (BIN_COUNT * _e7);
    let group_id = gid.x;
    if (group_id >= num_reduce_wgs) {
        return;
    }
    let num_reduce_wg_per_bin = (num_reduce_wgs / BIN_COUNT);
    let bin_id = (group_id / num_reduce_wg_per_bin);
    let bin_offset = (bin_id * _e5);
    let base_index = (((group_id % num_reduce_wg_per_bin) * ELEMENTS_PER_THREAD) * WG);
    loop {
        let _e23 = i;
        if (_e23 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e26 = i;
            let data_index = ((base_index + (_e26 * WG)) + local_id.x);
            let _e33 = i;
            let col = (((_e33 * WG) + local_id.x) / ELEMENTS_PER_THREAD);
            let _e40 = i;
            let row = (((_e40 * WG) + local_id.x) % ELEMENTS_PER_THREAD);
            let _e53 = counts[(bin_offset + data_index)];
            lds[row][col] = _e53;
        }
        continuing {
            let _e55 = i;
            i = (_e55 + 1u);
        }
    }
    workgroupBarrier();
    loop {
        let _e58 = i_1;
        if (_e58 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e62 = i_1;
            let tmp = lds[_e62][local_id.x];
            let _e69 = i_1;
            let _e73 = sum;
            lds[_e69][local_id.x] = _e73;
            let _e74 = sum;
            sum = (_e74 + tmp);
        }
        continuing {
            let _e77 = i_1;
            i_1 = (_e77 + 1u);
        }
    }
    let _e82 = sum;
    sums[local_id.x] = _e82;
    loop {
        let _e84 = i_2;
        if (_e84 < 8u) {
        } else {
            break;
        }
        {
            workgroupBarrier();
            let _e89 = i_2;
            if (local_id.x >= (1u << _e89)) {
                let _e95 = i_2;
                let _e99 = sums[(local_id.x - (1u << _e95))];
                let _e100 = sum;
                sum = (_e100 + _e99);
            }
            workgroupBarrier();
            let _e105 = sum;
            sums[local_id.x] = _e105;
        }
        continuing {
            let _e107 = i_2;
            i_2 = (_e107 + 1u);
        }
    }
    workgroupBarrier();
    let _e111 = reduced[group_id];
    sum = _e111;
    if (local_id.x > 0u) {
        let _e120 = sums[(local_id.x - 1u)];
        let _e121 = sum;
        sum = (_e121 + _e120);
    }
    loop {
        let _e124 = i_3;
        if (_e124 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e128 = i_3;
            let _e132 = sum;
            let _e133 = lds[_e128][local_id.x];
            lds[_e128][local_id.x] = (_e133 + _e132);
        }
        continuing {
            let _e136 = i_3;
            i_3 = (_e136 + 1u);
        }
    }
    workgroupBarrier();
    loop {
        let _e139 = i_4;
        if (_e139 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e142 = i_4;
            let data_index_1 = ((base_index + (_e142 * WG)) + local_id.x);
            let _e148 = i_4;
            let col_1 = (((_e148 * WG) + local_id.x) / ELEMENTS_PER_THREAD);
            let _e155 = i_4;
            let row_1 = (((_e155 * WG) + local_id.x) % ELEMENTS_PER_THREAD);
            if (data_index_1 < _e5) {
                let _e169 = lds[row_1][col_1];
                counts[(bin_offset + data_index_1)] = _e169;
            }
        }
        continuing {
            let _e171 = i_4;
            i_4 = (_e171 + 1u);
        }
    }
    return;
}

