// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-sort/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/sort_scan.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

const WG: u32 = 256u;
const BIN_COUNT: u32 = 16u;
const ELEMENTS_PER_THREAD: u32 = 4u;
const BLOCK_SIZE: u32 = 1024u;

@group(0) @binding(0) 
var<storage> num_keys_arr: array<u32>;
@group(0) @binding(1) 
var<storage, read_write> reduced: array<u32>;
var<workgroup> sums: array<u32, 256>;
var<workgroup> lds: array<array<u32, 256>, 4>;

fn div_ceil(a: u32, b: u32) -> u32 {
    return (((a + b) - 1u) / b);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(local_invocation_id) local_id: vec3<u32>, @builtin(workgroup_id) group_id: vec3<u32>) {
    var i: u32 = 0u;
    var sum: u32 = 0u;
    var i_1: u32 = 0u;
    var i_2: u32 = 0u;
    var i_3: u32 = 0u;
    var i_4: u32 = 0u;

    let num_keys = num_keys_arr[0];
    let _e5 = div_ceil(num_keys, BLOCK_SIZE);
    let _e7 = div_ceil(_e5, BLOCK_SIZE);
    let num_reduce_wgs = (BIN_COUNT * _e7);
    loop {
        let _e11 = i;
        if (_e11 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e14 = i;
            let data_index = ((_e14 * WG) + local_id.x);
            let _e20 = i;
            let col = (((_e20 * WG) + local_id.x) / ELEMENTS_PER_THREAD);
            let _e27 = i;
            let row = (((_e27 * WG) + local_id.x) % ELEMENTS_PER_THREAD);
            let _e39 = reduced[data_index];
            lds[row][col] = _e39;
        }
        continuing {
            let _e41 = i;
            i = (_e41 + 1u);
        }
    }
    workgroupBarrier();
    loop {
        let _e44 = i_1;
        if (_e44 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e48 = i_1;
            let tmp = lds[_e48][local_id.x];
            let _e55 = i_1;
            let _e59 = sum;
            lds[_e55][local_id.x] = _e59;
            let _e60 = sum;
            sum = (_e60 + tmp);
        }
        continuing {
            let _e63 = i_1;
            i_1 = (_e63 + 1u);
        }
    }
    let _e68 = sum;
    sums[local_id.x] = _e68;
    loop {
        let _e70 = i_2;
        if (_e70 < 8u) {
        } else {
            break;
        }
        {
            workgroupBarrier();
            let _e75 = i_2;
            if (local_id.x >= (1u << _e75)) {
                let _e81 = i_2;
                let _e85 = sums[(local_id.x - (1u << _e81))];
                let _e86 = sum;
                sum = (_e86 + _e85);
            }
            workgroupBarrier();
            let _e91 = sum;
            sums[local_id.x] = _e91;
        }
        continuing {
            let _e93 = i_2;
            i_2 = (_e93 + 1u);
        }
    }
    workgroupBarrier();
    sum = 0u;
    if (local_id.x > 0u) {
        let _e104 = sums[(local_id.x - 1u)];
        sum = _e104;
    }
    loop {
        let _e106 = i_3;
        if (_e106 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e110 = i_3;
            let _e114 = sum;
            let _e115 = lds[_e110][local_id.x];
            lds[_e110][local_id.x] = (_e115 + _e114);
        }
        continuing {
            let _e118 = i_3;
            i_3 = (_e118 + 1u);
        }
    }
    workgroupBarrier();
    loop {
        let _e121 = i_4;
        if (_e121 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e124 = i_4;
            let data_index_1 = ((_e124 * WG) + local_id.x);
            let _e129 = i_4;
            let col_1 = (((_e129 * WG) + local_id.x) / ELEMENTS_PER_THREAD);
            let _e136 = i_4;
            let row_1 = (((_e136 * WG) + local_id.x) % ELEMENTS_PER_THREAD);
            if (data_index_1 < num_reduce_wgs) {
                let _e149 = lds[row_1][col_1];
                reduced[data_index_1] = _e149;
            }
        }
        continuing {
            let _e151 = i_4;
            i_4 = (_e151 + 1u);
        }
    }
    return;
}

