// Adapted from Brush (https://github.com/ArthurBrussee/brush)
// Original: brush/crates/brush-sort/src/shaders/<file>
// Brush version: v0.3.0 (commit 3edecbb2fe79d3e2c87eeab85b15e0b1dd10d486)
// License: Apache-2.0 — see aether_cpp/third_party/brush/LICENSE
// Math source: gSplat reference kernels (3DGS paper, Kerbl et al. 2023)
//
// GENERATED by aether_cpp/scripts/wgsl_preprocess (Path G).
// Sources: aether_cpp/shaders/wgsl/_brush_raw/sort_reduce.wgsl
// To regenerate: cd aether_cpp/scripts/wgsl_preprocess && cargo run --release
// DO NOT hand-edit this file — edits are clobbered on re-run.
//

const WG: u32 = 256u;
const BIN_COUNT: u32 = 16u;
const ELEMENTS_PER_THREAD: u32 = 4u;
const BLOCK_SIZE: u32 = 1024u;

@group(0) @binding(0) 
var<storage> num_keys_arr: array<u32>;
@group(0) @binding(1) 
var<storage> counts: array<u32>;
@group(0) @binding(2) 
var<storage, read_write> reduced: array<u32>;
var<workgroup> sums: array<u32, 256>;

fn div_ceil(a: u32, b: u32) -> u32 {
    return (((a + b) - 1u) / b);
}

@compute @workgroup_size(256, 1, 1) 
fn main(@builtin(local_invocation_id) local_id: vec3<u32>, @builtin(workgroup_id) gid: vec3<u32>) {
    var sum: u32 = 0u;
    var i: u32 = 0u;
    var i_1: u32 = 0u;

    let num_keys = num_keys_arr[0];
    let _e5 = div_ceil(num_keys, BLOCK_SIZE);
    let _e7 = div_ceil(_e5, BLOCK_SIZE);
    let num_reduce_wgs = (BIN_COUNT * _e7);
    let group_id = gid.x;
    if (group_id >= num_reduce_wgs) {
        return;
    }
    let num_reduce_wg_per_bin = (num_reduce_wgs / BIN_COUNT);
    let bin_id = (group_id / num_reduce_wg_per_bin);
    let bin_offset = (bin_id * _e5);
    let base_index = ((group_id % num_reduce_wg_per_bin) * BLOCK_SIZE);
    loop {
        let _e21 = i;
        if (_e21 < ELEMENTS_PER_THREAD) {
        } else {
            break;
        }
        {
            let _e24 = i;
            let data_index = ((base_index + (_e24 * WG)) + local_id.x);
            if (data_index < _e5) {
                let _e36 = counts[(bin_offset + data_index)];
                let _e37 = sum;
                sum = (_e37 + _e36);
            }
        }
        continuing {
            let _e40 = i;
            i = (_e40 + 1u);
        }
    }
    let _e45 = sum;
    sums[local_id.x] = _e45;
    loop {
        let _e47 = i_1;
        if (_e47 < 8u) {
        } else {
            break;
        }
        {
            workgroupBarrier();
            let _e52 = i_1;
            if (local_id.x < (128u >> _e52)) {
                let _e58 = i_1;
                let _e62 = sums[(local_id.x + (128u >> _e58))];
                let _e63 = sum;
                sum = (_e63 + _e62);
                let _e68 = sum;
                sums[local_id.x] = _e68;
            }
        }
        continuing {
            let _e70 = i_1;
            i_1 = (_e70 + 1u);
        }
    }
    if (local_id.x == 0u) {
        let _e77 = sum;
        reduced[group_id] = _e77;
        return;
    } else {
        return;
    }
}

